# Generated by Django 4.2.1 on 2023-05-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IELTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='IELTS_rasm')),
                ('candidate_id', models.IntegerField()),
                ('date', models.DateField()),
                ('family_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=200)),
                ('region_address', models.CharField(max_length=200)),
                ('nationally', models.CharField(max_length=200)),
                ('first_language', models.CharField(max_length=200)),
                ('speaking', models.FloatField()),
                ('writing', models.FloatField()),
                ('reading', models.FloatField()),
                ('listening', models.FloatField()),
                ('admission', models.TextField()),
                ('test_number', models.FloatField()),
                ('candidate_number', models.FloatField()),
            ],
            options={
                'verbose_name': 'IELTS',
                'verbose_name_plural': 'IELTS',
            },
        ),
    ]
